version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - selenium-standalone-chrome
    networks:
      - my-network

  selenium-standalone-chrome:
    image: selenium/standalone-chrome:latest
    networks:
      - my-network

networks:
  my-network:
    driver: bridge