services:
  - type: web
    name: fastapi-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    ports:
      - 8000

  - type: pserv
    name: selenium-standalone-chrome
    env: docker
    dockerfilePath: ./Dockerfile.selenium
