services:
  - type: web
    name: fastapi-app
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: "/"
    plan: free

  - type: privateService
    name: selenium
    env: docker
    dockerfilePath: ./Dockerfile.selenium
    plan: free
