# Refactor the codes below in main.py to isolate at share_chat.py
from firebase_admin import firestore
import hashlib
from google.cloud.firestore_v1.base_query import FieldFilter
from fastapi import HTTPException, Request

### Share Chat Documentation
# This module contains functions to share a chat with another(possibly anonymous) user.
# The chat is shared by generating a unique hash for the chat, which is a combination of the user_id_hash and chat_id_hash.
# The user_id_hash is generated by hashing the user_id using sha256, and the chat_id_hash is generated by hashing the chat_id using sha256.
# The chat_ref_hash is generated by concatenating the user_id_hash and chat_id_hash with a delimiter "_".
# The chat_ref_hash is stored in the db, and can be used to retrieve the user_id and chat_id of the shared chat.
# The user_id and chat_id can be used to retrieve the chat from the db.
# This design ensures that the chat is shared securely, and the user_id and chat_id are not exposed to the shared user.
#
# This module contains the following functions:
# - store_and_get_chat_ref_hash: This function generates the chat_ref_hash and stores it in the db.
#   It returns the chat_ref_hash, which is used as a shareable link to the chat.
# - get_user_id_and_chat_id_from_chat_ref_hash: This function retrieves the user_id and chat_id from the chat_ref_hash.
#   It returns the user_id and chat_id, which can be used to retrieve the chat from the db.


def store_and_get_chat_ref_hash(
    request: Request, user_id: str, chat_id: str, db: firestore.client
):
    try:
        if not request.state.user:
            raise HTTPException(
                status_code=500, detail="User info not set in request state"
            )

        # Log to confirm user info is set before external API calls
        # print("Authenticated user info:", request.state.user)

        # Encode the chatRef to chat_hash
        user_id_hash = hashlib.sha256(user_id.encode()).hexdigest()
        chat_id_hash = hashlib.sha256(chat_id.encode()).hexdigest()

        # To concatenate the user_id_hash and chat_id_hash, we will use the delimiter "_"
        chat_ref_hash = user_id_hash + "_" + chat_id_hash

        # Store the hash in the db
        user_doc = db.collection("Users").document(user_id)
        chat_doc = user_doc.collection("Chats").document(chat_id)

        user_doc.update({"userIdHash": user_id_hash})
        chat_doc.update({"isShared": True, "chatIdHash": chat_id_hash})

        return {"chat_ref_hash": chat_ref_hash}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Error sharing chat: {str(e)}")


def get_user_id_and_chat_id_from_chat_ref_hash(
    chat_ref_hash: str, db: firestore.client
):
    try:
        # Split the chat_ref_hash to get the user_id_hash and chat_id_hash
        user_id_hash, chat_id_hash = chat_ref_hash.split("_")

        # Find the user_id from the user_id_hash
        user_id = None
        try:
            user_docs = db.collection("Users").get()
            for user_doc in user_docs:
                try:
                    if user_doc.get("userIdHash") == user_id_hash:
                        user_id = user_doc.id
                        break
                except Exception as e:
                    continue

        except Exception as e:
            raise HTTPException(
                status_code=404, detail="Shared chat not found: User no longer exists"
            )
        if user_id is None:
            raise HTTPException(
                status_code=404, detail="Shared chat not found: User no longer exists"
            )

        # Find the chat_id by iterating through the chats of the user, and checking if the chat_id_hash matches
        chat_id = None
        try:
            chat_docs = (
                db.collection("Users").document(user_id).collection("Chats").get()
            )
            for chat_doc in chat_docs:
                if chat_doc.get("chatIdHash") == chat_id_hash:
                    chat_id = chat_doc.id
                    break
        except Exception as e:
            raise HTTPException(
                status_code=404,
                detail="Shared chat not found: User seems to have revoked access to the chat",
            )

        return {"user_id": user_id, "chat_id": chat_id}

    except Exception as e:
        raise HTTPException(
            status_code=500, detail=f"Error viewing shared chat: {str(e)}"
        )
