import json
from datetime import datetime
from typing import List, Dict
import os
from dotenv import load_dotenv
from model.forecast_request import ForecastRequest
from model.article import Article
from openai import OpenAI
from query_to_answer.prompt import planner_prompt, publisher_prompt

class ForecastGenerator:
    """
    A class to generate forecasts based on news articles using a language model (LLM).

    Attributes:
        client (any): The LLM client used to generate completions and summaries.
        model (str): The LLM model name, default is 'gpt-4'.
        planner_prompt (str): The prompt template used for planning.
        publisher_prompt (str): The prompt template used for generating forecasts.
        GOOGLE_SEARCH_DATE_FORMAT (str): The date format for Google search dates.
    """
    def __init__(self, client: any, model: str = "gpt-4"):
        """
        Initializes ForecastGenerator with an LLM client and model.

        Args:
            client (any): The LLM client used to interact with the language model.
            model (str): The name of the LLM model to use, default is "gpt-4".
        """
        # Initialize LLM client
        self.model = model
        self.client = client

        # Load prompts
        self.planner_prompt = planner_prompt
        self.publisher_prompt = publisher_prompt

        self.GOOGLE_SEARCH_DATE_FORMAT = "%Y-%m-%d"

    def format_articles_for_llm(self, articles: Dict[str, List[Article]]) -> str:
        """
        Formats articles into a string format suitable for input to the LLM.

        Args:
            articles (Dict[str, List[Article]]): A dictionary of article lists by source.

        Returns:
            str: A formatted string of articles with key details such as title, query, and published date.
        """
        formatted_results = []
        id_counter = 1

        for source, article_list in articles.items():
            for article in article_list:
                summarized_text = self.summarize_article(article.content.get('text', ''))
                content = f"""ID: {id_counter}
Query: {article.query}
Title: {article.title}
Date: {article.published_date}
Source: {source}
Content:
[start content]
{summarized_text}
[end content]"""
                formatted_results.append(content)
                id_counter += 1

        return "\n\n----\n\n".join(formatted_results)

    def summarize_article(self, article_content: str) -> str:
        """
        Summarizes the content of an article to a maximum of 250 words.

        Args:
            article_content (str): The full text of the article.

        Returns:
            str: A 250-word summary generated by the LLM.
        """
        # Define the prompt for summarization
        prompt = f"Please summarize the following article to 250 words:\n\n{article_content}"

        # Get the LLM response
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}]
        ).to_dict()["choices"][0]["message"]["content"]

        # Print the summarized content for debugging purposes
        print(f"Summarized Content (250 words):\n{response.strip()}")

        return response.strip()

    def extract_prediction(self, response: str) -> float:
        """
        Extracts the forecast prediction value from the LLM response.

        Args:
            response (str): The response from the LLM, expected to contain a prediction in <answer> tags.

        Returns:
            float: The extracted prediction value, or None if extraction fails.
        """
        import re
        # Look for the prediction between <answer> tags
        answer_match = re.search(r'<answer>\s*\*([0-9.]+)\*\s*</answer>', response)
        if answer_match:
            return float(answer_match.group(1))
        return None

    def extract_rationale(self, response: str) -> str:
        """
        Extracts the rationale for the forecast from the LLM response.

        Args:
            response (str): The response from the LLM, expected to contain rationale sections in tags.

        Returns:
            str: A formatted string with key facts, reasons for and against, and analysis from the response.
        """
        import re
        # Combine facts, reasons, and thinking sections
        sections = []

        facts_match = re.search(r'<facts>(.*?)</facts>', response, re.DOTALL)
        if facts_match:
            sections.append("Key Facts:\n" + facts_match.group(1).strip())

        no_match = re.search(r'<no>(.*?)</no>', response, re.DOTALL)
        if no_match:
            sections.append("Reasons Against:\n" + no_match.group(1).strip())

        yes_match = re.search(r'<yes>(.*?)</yes>', response, re.DOTALL)
        if yes_match:
            sections.append("Reasons For:\n" + yes_match.group(1).strip())

        thinking_matches = re.findall(r'<thinking>(.*?)</thinking>', response, re.DOTALL)
        if thinking_matches:
            sections.append("Analysis:\n" + "\n".join(thinking_matches))

        return "\n\n".join(sections)

    def generate_forecast(self, request: ForecastRequest, news: Dict[str, List[Article]]) -> dict:
        """
        Generates a forecast based on the provided news articles and forecast request.

        Args:
            request (ForecastRequest): The forecast request containing the question and parameters.
            news (Dict[str, List[Article]]): A dictionary of collected news articles by source.

        Returns:
            dict: A dictionary containing the forecast answer with rationale, prediction, and source information.
        """
        # Format the articles for the LLM
        formatted_sources = self.format_articles_for_llm(news)

        # Prepare the publishing prompt
        today_string = datetime.now().strftime(self.GOOGLE_SEARCH_DATE_FORMAT)
        publishing_query = self.publisher_prompt.format(
            sources=formatted_sources,
            today=today_string,
            question=request.question
        )

        # Retry mechanism to avoid situations when it fails to extract prediction
        prediction = None
        attempts = 0
        max_attempts = 3

        while not prediction and attempts < max_attempts:
            attempts += 1
            # Get LLM response
            # Note: Implementation depends on your LLM client
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": publishing_query}]
            ).to_dict()["choices"][0]["message"]["content"]

            # Print the summarized content for debugging purposes
            print(f"LLM Response:\n{response}")

            # Extract prediction and rationale
            prediction = self.extract_prediction(response)
            rationale = self.extract_rationale(response)

        if not prediction:
            raise ValueError("Failed to extract prediction after 3 attempts")

        # Format the answer
        answer = {
            "Question": request.question,
            "Forecaster ID": "AI-Forecaster",  # You might want to make this configurable
            "Forecaster Rationale": rationale,
            "Forecast": f"{prediction * 100:.1f}%",
            "Sources": {
                source: [
                    {
                        "title": article.title,
                        "content": article.content,
                        "url": article.url,
                        "published_date": article.published_date,
                        "platform": article.platform
                    }
                    for article in articles
                ]
                for source, articles in news.items()
            }
        }

        return {
            "answer": answer,
            "raw_response": response  # Including raw response for debugging/logging
        }
