import json
from datetime import datetime
from typing import List, Dict
import os
from dotenv import load_dotenv
from model.forecast_request import ForecastRequest
from model.article import Article
from openai import OpenAI
from query_to_answer.prompt import planner_prompt, publisher_prompt

class ForecastGenerator:
    """
    A class to generate forecasts based on news articles using a language model (LLM).

    Attributes:
        client (any): The LLM client used to generate completions and summaries.
        model (str): The LLM model name, default is 'gpt-4'.
        planner_prompt (str): The prompt template used for planning.
        publisher_prompt (str): The prompt template used for generating forecasts.
        GOOGLE_SEARCH_DATE_FORMAT (str): The date format for Google search dates.
    """
    def __init__(self, client: any, model: str = "gpt-4"):
        """
        Initializes ForecastGenerator with an LLM client and model.

        Args:
            client (any): The LLM client used to interact with the language model.
            model (str): The name of the LLM model to use, default is "gpt-4".
        """
        # Initialize LLM client
        self.model = model
        self.client = client

        # Load prompts
        self.planner_prompt = planner_prompt
        self.publisher_prompt = publisher_prompt

        self.GOOGLE_SEARCH_DATE_FORMAT = "%Y-%m-%d"
        self.article_summaries = {}

    def format_articles_for_llm(self, articles: Dict[str, List[Article]]) -> str:
        """
        Formats articles into a string format suitable for input to the LLM.

        Args:
            articles (Dict[str, List[Article]]): A dictionary of article lists by source.

        Returns:
            str: A formatted string of articles with key details such as title, query, and published date.
        """
        formatted_results = []
        id_counter = 1
        self.article_summaries = {}  # Reset article summaries

        for source, article_list in articles.items():
            for article in article_list:
                summarized_text = self.summarize_article(article.content.get('text', ''))
                # Store summary with ID
                self.article_summaries[str(id_counter)] = {
                    "summary": summarized_text,
                    "full_text": article.content.get('text', ''),
                    "title": article.title,
                    "source": source,
                    "date": article.published_date
                }

                content = f"""ID: {id_counter}
Query: {article.query}
Title: {article.title}
Date: {article.published_date}
Source: {source}
Content:
[start content]
{summarized_text}
[end content]"""
                formatted_results.append(content)
                id_counter += 1

        return "\n\n----\n\n".join(formatted_results)

    def summarize_article(self, article_content: str) -> str:
        """
        Summarizes the content of an article to a maximum of 250 words.

        Args:
            article_content (str): The full text of the article.

        Returns:
            str: A 250-word summary generated by the LLM.
        """
        # Define the prompt for summarization
        prompt = f"Please summarize the following article to 250 words:\n\n{article_content}"

        # Get the LLM response
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}]
        ).to_dict()["choices"][0]["message"]["content"]

        # Print the summarized content for debugging purposes
        print(f"Summarized Content (250 words):\n{response.strip()}")

        return response.strip()

    def extract_prediction(self, response: str) -> float:
        """
        Extracts the forecast prediction value from the LLM response.

        Args:
            response (str): The response from the LLM, expected to contain a prediction in <answer> tags.

        Returns:
            float: The extracted prediction value, or None if extraction fails.
        """
        import re
        # Look for the prediction between <answer> tags
        answer_match = re.search(r'<answer>\s*\*([0-9.]+)\*\s*</answer>', response)
        if answer_match:
            return float(answer_match.group(1))
        return None

    def extract_rationale(self, response: str) -> str:
        """
        Extracts the rationale for the forecast from the LLM response.

        Args:
            response (str): The response from the LLM, expected to contain rationale sections in tags.

        Returns:
            str: A formatted string with key facts, reasons for and against, and analysis from the response.
        """
        import re
        # Combine facts, reasons, and thinking sections
        sections = []

        facts_match = re.search(r'<facts>(.*?)</facts>', response, re.DOTALL)
        if facts_match:
            sections.append("Key Facts:\n" + facts_match.group(1).strip())

        no_match = re.search(r'<no>(.*?)</no>', response, re.DOTALL)
        if no_match:
            sections.append("Reasons Against:\n" + no_match.group(1).strip())

        yes_match = re.search(r'<yes>(.*?)</yes>', response, re.DOTALL)
        if yes_match:
            sections.append("Reasons For:\n" + yes_match.group(1).strip())

        thinking_matches = re.findall(r'<thinking>(.*?)</thinking>', response, re.DOTALL)
        if thinking_matches:
            sections.append("Analysis:\n" + "\n".join(thinking_matches))

        return "\n\n".join(sections)


    def format_response(self, response: str) -> str:
        """
        Example response: <facts> - NASA's Artemis program aims to return humans to the Moon, with Artemis III set for late 2026 as the first crewed mission. - NASA has selected SpaceX and Blue Origin to develop Human Landing Systems (HLS) for lunar missions. - Blue Origin is involved in delivering a lunar habitat by 2033, while SpaceX will support lunar rover and cargo missions. - NASA's Space Launch System (SLS) is crucial for Artemis missions despite criticism regarding costs and delays. - Lockheed Martin is developing a lunar solar array technology as part of the Artemis program to support sustainable human presence on the Moon. - There is ongoing debate regarding the cost-effectiveness of the SLS and the feasibility of utilizing alternative launch technologies for future missions. - NASA's Artemis program is seen as a precursor to more ambitious goals such as Mars missions. </facts> <no> 1. Significant budget constraints and political debates over funding the Artemis program could delay or even cancel the planned missions. (Strength: 8/10) 2. The development and testing of new launch systems (like SpaceX's Starship and Blue Origin's Blue Moon lander) may face unforeseen technical challenges that could impede timelines. (Strength: 7/10) 3. Previous delays in the Space Launch System (SLS) and uncertainties surrounding its operational efficiency may hinder mission execution. (Strength: 6/10) </no> <yes> 1. NASA's selection of SpaceX and Blue Origin demonstrates a commitment to leveraging commercial partnerships, which may enhance innovation and reduce risk. (Strength: 8/10) 2. The current timeline indicates positive advancements, with Artemis III scheduled for 2026, maintaining a structured approach to lunar exploration. (Strength: 9/10) 3. Technological innovations such as Lockheed Martin's lunar solar arrays may improve operational capabilities, making sustained human presence more feasible. (Strength: 7/10) </yes> <thinking1> The forecast for whether NASA will land humans on the Moon hinges on several factors, including technological advancements, budget constraints, and the viability of partnerships with commercial entities. The Strength of reasons leaning towards a positive outcome (like timelines and commercial partnerships) suggests optimism about achieving the goal. However, significant funding hurdles and technical complications present serious risks. Considering the recent announcements and the framework outlined by NASA, there is a strong indication that plans are moving forward despite some existing uncertainties. The strength of the arguments for success (particularly the advancements in technology and NASA's commitment to its Artemis program) balances against the potential for failure due to political and financial discussions. The optimism surrounding commercial involvement adds a layer of reliability that was previously less certain. Overall, my thinking reflects a conflict between cautious optimism and serious risks. While there are strong positive indicators, the overarching uncertainties warrant a measured approach to predicting the outcome. Given that significant progress is expected in the near future while retaining awareness of potential pitfalls, I will adjust my forecast to reflect a reasonably optimistic outlook. </thinking1> <t tentiative>0.75</tentative> <thinking2> Upon reflection, my earlier assessment of 0.75 captures a moderately confident likelihood of success based on the available evidence. However, weighing the potential dangers of funding shortfalls and technological setbacks should compel me to lower this assessment slightly. A 75% probability assumes ideal growth and smooth execution, but the reality often presents more challenges that might lower this figure. Given the projected mission timelines, consistent backing from NASA, and technological progress in the existing projects, a final adjustment considers both the difficulties and the momentum behind the Artemis program. A final probability may more appropriately reflect a solid expectation of success while acknowledging manageable risks, leading to a re-evaluation of my forecast. </thinking2> <answer>*0.7*</answer>
        Return a formatted response

        Some of the tags:
        <facts>
        <no>
        <yes>
        <thinking1>
        <tentative>
        <thinking2>
        <answer>
        Ex)
        Facts.
        ...

        Reasons Against.
        ...

        Reasons For.
        ...

        Analysis 1.
        ...

        Tentative Prediction.
        ...

        Analysis 2.
        ...

        Final Prediction.
        """
        import re
        # Combine facts, reasons, and thinking sections
        sections = []

        facts_match = re.search(r'<facts>(.*?)</facts>', response, re.DOTALL)
        if facts_match:
            sections.append("Facts:\n" + facts_match.group(1).strip())

        no_match = re.search(r'<no>(.*?)</no>', response, re.DOTALL)
        if no_match:
            sections.append("Reasons Against:\n" + no_match.group(1).strip())

        yes_match = re.search(r'<yes>(.*?)</yes>', response, re.DOTALL)
        if yes_match:
            sections.append("Reasons For:\n" + yes_match.group(1).strip())

        thinking_matches = re.findall(r'<thinking(.*?)>(.*?)</thinking\1>', response, re.DOTALL)
        if thinking_matches:
            sections.append("Analysis:\n" + "\n".join([match[1] for match in thinking_matches]))

        tentative_match = re.search(r'<tentative>(.*?)</tentative>', response)
        if tentative_match:
            sections.append("Tentative Prediction:\n" + tentative_match.group(1).strip())

        final_match = re.search(r'<answer>\s*\*([0-9.]+)\*\s*</answer>', response)
        if final_match:
            sections.append("Final Prediction:\n" + final_match.group(1).strip())

        return "\n\n".join(sections)


    def generate_forecast(self, request: ForecastRequest, news: Dict[str, List[Article]]) -> dict:
        """
        Generates a forecast based on the provided news articles and forecast request.

        Args:
            request (ForecastRequest): The forecast request containing the question and parameters.
            news (Dict[str, List[Article]]): A dictionary of collected news articles by source.

        Returns:
            dict: A dictionary containing the forecast answer with rationale, prediction, and source information.
        """
        response = ""

        # Format the articles for the LLM
        formatted_sources = self.format_articles_for_llm(news)

        # Prepare the publishing prompt
        today_string = datetime.now().strftime(self.GOOGLE_SEARCH_DATE_FORMAT)
        publishing_query = self.publisher_prompt.format(
            sources=formatted_sources,
            today=today_string,
            question=request.question
        )

        # Retry mechanism to avoid situations when it fails to extract prediction
        prediction = None
        attempts = 0
        max_attempts = 3

        while not prediction and attempts < max_attempts:
            attempts += 1
            # Get LLM response
            # Note: Implementation depends on your LLM client
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": publishing_query}]
            ).to_dict()["choices"][0]["message"]["content"]

            # Print the summarized content for debugging purposes
            print(f"LLM Response:\n{response}")

            # Extract prediction and rationale
            prediction = self.extract_prediction(response)
            rationale = self.extract_rationale(response)

        if not prediction:
            raise ValueError("Failed to extract prediction after 3 attempts")

        # Format the answer
        answer = {
            "Question": request.question,
            "Forecaster ID": "AI-Forecaster",  # You might want to make this configurable
            "Forecaster Rationale": rationale,
            "Forecast": f"{prediction * 100:.1f}%",
            "Sources": {
                source: [
                    {
                        "title": article.title,
                        "content": article.content,
                        "url": article.url,
                        # Some attributes for metrics (e.g., relevance score, ranking out of number of articles of this source type(platform)), etc.
                        "published_date": article.published_date,
                        "platform": article.platform,
                        "publisher_title": article.publisher["title"],
                        "publisher_href": article.publisher["href"],
                        "relevance_score": article.score,
                        "ranking": i + 1,
                        "total_articles_of_source": len(articles),
                    }
                    for i, article in enumerate(articles)
                ]
                for source, articles in news.items()
            }
        }

        response = self.format_response(response)
        return {
            "answer": answer,
            "raw_response": response,  # Including raw response for debugging/logging
            "article_summaries": self.article_summaries,
        }
